Repository pa-rang/kyrics-frontend, pull requests merged in 2021-08, with the labels that each got.

#63 fix: autoplay 제거
  pages/study/[id].tsx
Labels: 🔥 hotfix

#68 fix: 렌더 시 볼륨 바 깜빡거리는 에러 해결
  components/study/PlayController.tsx
Labels: 🛠 fix

#67 feat: mobile keyExpression 구현
  .eslintrc.json
  components/common/LoginModal.tsx
  components/study/KeyExpression/FavoriteButton.tsx
  components/study/KeyExpression/KeyExpressionItem.tsx
  components/study/KeyExpression/index.tsx
  components/study/Lyrics.tsx
  components/study/MobilePlayer/MobileKeyExpression.tsx
  components/study/MobilePlayer/MobileModal.tsx
  components/study/MobilePlayer/MobileModal2.tsx
  components/study/MobilePlayer/MobilePlayController.tsx
  components/study/MobilePlayer/MobilePlayerBottom.tsx
  components/study/PlayerBtns.tsx
  components/study/mobilePlayer.tsx
  pages/study/[id].tsx
  states/index.ts
Labels: 🥝. feature

#70 fix: 언어선택 dropdown 위치 조절
  components/study/Lyrics.tsx
Labels: 🛠 fix

#71 fix: 모바일 플레이어 버튼 드롭다운 사이즈 축소
  components/study/MobilePlayer/MobileModal2.tsx
Labels: 🛠 fix

#72 Fix: 헤더 모바일 드롭다운 구현
  components/common/ProfileMenu.tsx
  public/assets/icons/IcMobileMySong.svg
  public/assets/icons/IcMobileMyVoca.svg
  public/assets/icons/IcMobileSetting.svg
Labels: 🛠 fix

#73 fix: autplay 추가
  components/study/PlayController.tsx
  pages/study/[id].tsx
Labels: 🔥 hotfix

#74 hotfix: 모바일 유튜브 에러 해결 시도
  components/study/MobilePlayer/MobilePlayController.tsx
  components/study/MobilePlayer/MobilePlayer.tsx
  components/study/MobilePlayer/MobilePlayerBottom.tsx
  components/study/MobilePlayer/MobilePlayerTop.tsx
  components/study/PlayController.tsx
  components/study/Player.tsx
  pages/study/[id].tsx
  pages/test/index.tsx
  types/index.ts
Labels: 🔥 hotfix

#75 fix: study componentDidMount, Duration 값 바로 들어오도록 수정
  pages/study/[id].tsx
Labels: 🛠 fix

#76 Fix: 모달 바깥쪽 클릭시 모달 Close
  components/common/Header.tsx
  components/common/ProfileMenu.tsx
Labels: 🛠 fix

#77 Fix: 모바일 헤 드롭다운 사이즈 확대
  components/common/ProfileMenu.tsx
  public/assets/icons/IcMobileMySong.svg
  public/assets/icons/IcMobileMyVoca.svg
  public/assets/icons/IcMobileSetting.svg
Labels: 🛠 fix

#78 feat: 모바일 more Btn 모달 바깥쪽 클릭시 모달 내려가도록 구현
  components/common/ProfileMenu.tsx
  components/study/MobilePlayer/MobileModal.tsx
  components/study/MobilePlayer/MobileModal2.tsx
  components/study/MobilePlayer/MobilePlayController.tsx
  components/study/PlayerBtns.tsx
  hooks/useModalOutSideClick.tsx
  pages/test/index.tsx
Labels: 🥝. feature, 🛠 fix

#79 Refact/artist card
  components/artist/MusicCard.tsx
  components/home/ArtistCard.tsx
  components/home/NewSongCard.tsx
Labels: 💻 refactor

#80 Fix: 영어 문장이 2줄 일때 모두 보이도록 수정
  components/study/KeyExpression/KeyExpressionItem.tsx
Labels: 🛠 fix

#82 hotfix: 모바일에서 artist 2번 클릭해야 넘어가는 해결
  components/home/ArtistCard.tsx
Labels: 🔥 hotfix

#84 Refact: Lyrics
  components/mypage/mysong/MySongItem.tsx
  components/study/Lyrics.tsx
  components/study/LyricsContainer/LyricsContent/Lyrics.tsx
  components/study/LyricsContainer/LyricsContent/TextSizeController.tsx
  components/study/LyricsContainer/LyricsContent/Translate.tsx
  components/study/LyricsContainer/LyricsContent/index.tsx
  components/study/LyricsContainer/Steps.tsx
  components/study/LyricsContainer/index.tsx
  components/study/MiniPlayer.tsx
  components/study/MobilePlayer/MobileKeyExpression.tsx
  components/study/MobilePlayer/MobilePlayerTop.tsx
  components/study/PlayController.tsx
  components/study/Player.tsx
  components/study/PlayerBtns.tsx
  hooks/api.ts
  hooks/useMeasureWidth.ts
  hooks/useModalSize.ts
  pages/study/[id].tsx
Labels: 💻 refactor
