Repository pa-rang/kyrics-frontend, pull requests merged in 2021-07, with the labels that each got.

#1 dev: eslint prettier 설정
  .eslintrc.json
  .prettierrc.json
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/index.tsx
  styles/globals.css
  tsconfig.json
  yarn.lock
Labels: enhancement

#2 docs: PR 템플릿 작성
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📝. docs

#3 dev: stylelint 및 concentric-order config 적용
  .stylelintrc
  package.json
  yarn.lock
Labels: 🚀 dev

#4 dev: 파일 구조 세팅
  components/home/Title.tsx
  hooks/useExample.ts
  lib/constants/example.ts
  lib/utils/example.ts
  pages/index.tsx
  public/assets/icons/favicon.ico
  public/assets/images/example.ts
  styles/globals.css
  types/index.ts
  yarn.lock
Labels: 🚀 dev

#5 docs: Readme 작성
  README.md
Labels: 📝. docs

#6 dev: study 뷰 폴더구조 짜기
  components/study/Lyrics.tsx
  components/study/Player.tsx
  components/study/PlayerBtns.tsx
  pages/study.tsx
  tsconfig.json
Labels: 🚀 dev

#7 dev: `json-server`세팅 및 테스트
  json-server/mock-api.json
  lib/api.ts
  package.json
  pages/index.tsx
  types/index.ts
  yarn.lock
Labels: 🚀 dev

#8 feat: 헤더 퍼블리싱 & 간단한 기능 구현
  components/common/Header.tsx
  components/common/ProfileMenu.tsx
  pages/index.tsx
  public/assets/icons/IcDefaultProfile.svg
  public/assets/icons/IcMySong.svg
  public/assets/icons/IcMyVoca.svg
  public/assets/icons/IcSetting.svg
  public/assets/icons/headerLogo.svg
Labels: 🥝. feature

#11 chore: Return type을 필수로 넣어줘야하는 eslint option 제거
  .eslintrc.json
Labels: 🚀 dev

#10 feat: 메인 플레이어 구현
  components/study/Player.tsx
  components/study/PlayerBtns.tsx
  package.json
  pages/study.tsx
  public/assets/icons/backIcon.svg
  public/assets/icons/forwardIcon.svg
  public/assets/icons/pauseIcon.svg
  public/assets/icons/playIcon.svg
  public/assets/icons/replayIcon.svg
  public/assets/icons/soundIcon.svg
  public/assets/images/exampleImg.svg
  public/assets/images/playerBackground.svg
  tsconfig.json
  yarn.lock
Labels: 🥝. feature

#14 fix: player-btns conflict 해결
  components/study/Player.tsx
  components/study/PlayerBtns.tsx
  tsconfig.json
Labels: 🥝. feature

#12 feat: footer 구현
  components/common/Footer.tsx
  pages/index.tsx
  public/assets/icons/emailIcon.svg
  public/assets/icons/githubIcon.svg
  public/assets/icons/kyricsGrayLogo.svg
  public/assets/icons/kyricsGrayName.svg
Labels: 🥝. feature

#13 feat(study): lyrics - player 연결
  components/study/Lyrics.tsx
  components/study/Player.tsx
  components/study/Quiz.tsx
  pages/study.tsx
  public/assets/icons/Alphabet.svg
  public/assets/icons/dropDownIcon.svg
  public/assets/icons/offStep1.svg
  public/assets/icons/offStep2.svg
  public/assets/icons/onStep1.svg
  public/assets/icons/onStep2.svg
  public/assets/icons/sizeDown.svg
  public/assets/icons/sizeUp.svg
  public/assets/index.ts
  tsconfig.json
  types/index.ts
Labels: 🥝. feature

#19 feat(mypage): my song item 구현
  components/mypage/mysong/MySongItem.tsx
  public/assets/icons/mySongStar.svg
Labels: 🥝. feature

#21 feat(footer): 반응형 footer 구현
  components/common/Footer.tsx
  pages/mypage/collection.tsx
Labels: 🥝. feature

#15 feat: 아티스트 뷰 구현
  components/artist/ArtistBanner.tsx
  components/artist/MusicCard.tsx
  components/artist/NewlyAdded.tsx
  json-server/mock-api.json
  pages/artist/[id].tsx
  public/assets/icons/playBtn.svg
  types/index.ts
Labels: 🥝. feature

#22 feat(header): 반응형 구현, router 등록
  components/common/Header.tsx
  components/common/ProfileMenu.tsx
  public/assets/icons/SmallHeaderLogo.svg
Labels: 🥝. feature

#20 feat: My Songs , My Vocab 전체뷰 구현
  components/mypage/mysong/MySongItem.tsx
  components/mypage/mysong/MyVocab.tsx
  json-server/mock-api.json
  package.json
  pages/mypage/collection.tsx
  types/index.ts
  yarn.lock
Labels: 🥝. feature

#23 디자인 1차 QA 반영
  components/common/Footer.tsx
  components/common/Header.tsx
  components/home/ArtistCard.tsx
  components/home/ArtistCarousel.tsx
  components/home/Title.tsx
  components/mypage/mysong/MySongItem.tsx
  components/study/Lyrics.tsx
  components/study/Player.tsx
  components/study/PlayerBtns.tsx
  components/study/YoutubeModal.tsx
  json-server/mock-api.json
  pages/index.tsx
  pages/mypage/collection.tsx
Labels: 💅🏻 style

#24 feat: home, artist 뷰 서버 연결
  components/artist/ArtistBanner.tsx
  components/artist/MusicCard.tsx
  components/artist/NewlyAdded.tsx
  components/home/ArtistCard.tsx
  components/home/ArtistCarousel.tsx
  json-server/mock-api.json
  pages/artist/[id].tsx
  pages/index.tsx
  types/index.ts
Labels: 🥝. feature

#25 feat: my page- settings 뷰 구현
  components/settings/Main.tsx
  json-server/mock-api.json
  pages/mypage/settings.tsx
  public/assets/icons/deleteIcon.svg
  public/assets/icons/editIcon.svg
  public/assets/images/profileExample.svg
Labels: 🥝. feature

#26 feat: study 가사 서버 연결
  components/study/Lyrics.tsx
  components/study/PlayController.tsx
  components/study/Player.tsx
  components/study/PlayerBtns.tsx
  components/study/Quiz.tsx
  components/study/YoutubeModal.tsx
  json-server/mock-api.json
  pages/_app.tsx
  pages/study.tsx
  pages/study/[id].tsx
  public/assets/icons/favoriteSong.svg
  public/assets/icons/onFavoriteIcon.svg
  states/index.ts
  types/index.ts
Labels: 🥝. feature

#29 fix: 플레이어 라우팅 아이디 값에 따라 들어오는 정보 바뀌도록 수정
  components/study/PlayController.tsx
  components/study/Player.tsx
  pages/study/[id].tsx
Labels: 🛠 fix

#30 feat: 홈, 아티스트 모바일 반응형 구현
  components/artist/ArtistBanner.tsx
  components/artist/MusicCard.tsx
  components/artist/NewlyAdded.tsx
  components/home/ArtistCard.tsx
  components/home/ArtistCarousel.tsx
  components/home/NewSongCard.tsx
  components/home/Title.tsx
  pages/artist/[id].tsx
Labels: 🥝. feature

#31 fix: 호버 디폴트, 헤더 반응형 수정
  components/common/Header.tsx
  components/home/ArtistCard.tsx
Labels: 🔥 hotfix

#36 fix(footer): 반응형 시 로고 사이즈, margin 조절
  components/common/Footer.tsx
  public/assets/icons/kyricsSmallGrayName.svg
Labels: 🥝. feature

#37 feat: study view에서 keyExpressions와 lyrics 병치
  components/study/KeyExpression/index.tsx
  components/study/Lyrics.tsx
  pages/mypage/collection.tsx
  pages/study/[id].tsx
Labels: 🥝. feature

#35 feat: my vocab 서버 연결
  components/common/ProfileMenu.tsx
  components/mypage/mysong/MyVocab.tsx
  components/mypage/mysong/Mysong.tsx
  components/mypage/myvocab/MyVocab.tsx
  components/mypage/myvocab/MyVocabItem.tsx
  components/study/KeyExpression/FavoriteButton.tsx
  components/study/KeyExpression/KeyExpressionItem.tsx
  components/study/KeyExpression/index.tsx
  json-server/mock-api.json
  pages/mypage/MyVocab.tsx
  pages/mypage/collection.tsx
  public/assets/index.ts
  types/index.ts
Labels: 🥝. feature

#39 fix: 즐겨찾기 post api 코드 제거
  components/study/KeyExpression/FavoriteButton.tsx
  components/study/KeyExpression/KeyExpressionItem.tsx
Labels: 🛠 fix

#40 feat(mysong): 즐겨찾기 post, delete 구현
  components/artist/ArtistBanner.tsx
  components/artist/MusicCard.tsx
  components/mypage/mysong/Mysong.tsx
  components/mypage/myvocab/MyVocab.tsx
  components/study/Lyrics.tsx
  components/study/PlayerBtns.tsx
  pages/mypage/collection.tsx
  pages/study/[id].tsx
Labels: 🥝. feature

#41 feat(mysong): mobile 뷰 구현
  components/mypage/mysong/MySongItem.tsx
  components/mypage/mysong/Mysong.tsx
  pages/mypage/collection.tsx
  public/assets/icons/mySmallSongStar.svg
Labels: 🥝. feature

#42 feat(myvocab): mobile 뷰 구현
  components/mypage/myvocab/MyVocab.tsx
  components/mypage/myvocab/MyVocabItem.tsx
Labels: 🥝. feature

#43 feat: connect mysongs server
  components/mypage/mysong/MySongItem.tsx
  components/mypage/mysong/Mysong.tsx
  components/mypage/myvocab/MyVocab.tsx
  components/study/PlayerBtns.tsx
  pages/study/[id].tsx
Labels: 🥝. feature

#46 feat(mysongs): 노래 클릭 시 route 구현
  components/mypage/mysong/MySongItem.tsx
Labels: 🥝. feature

#47 feat(settings): 계정 삭제 기능, 이메일 수정 기능 구현
  components/settings/Main.tsx
Labels: 🥝. feature

#48 feat(player): copy link 추가
  components/study/PlayerBtns.tsx
Labels: 🥝. feature

#50 feat(lyrics): quiz 가운데 정렬
  components/study/Lyrics.tsx
Labels: 🥝. feature

#51 fix: keyexpression 아이콘 수정
  components/study/KeyExpression/FavoriteButton.tsx
  public/assets/icons/FavoriteIcon2.svg
  public/assets/icons/FavoriteYellowIcon.svg
  public/assets/index.ts
Labels: 💅🏻 style

#52 feat: 로그인 안 되었을 때, 즐겨찾기 버튼 누르면 login modal 띄우기
  components/common/LoginModal.tsx
  components/study/KeyExpression/FavoriteButton.tsx
  components/study/PlayerBtns.tsx
Labels: 🥝. feature

#55 feat: 이메일 변경 확인 모달 구현
  components/login/RegisterEmailInput.tsx
  components/login/SubscribeModal.tsx
  components/settings/Main.tsx
  components/study/PlayerBtns.tsx
Labels: 🥝. feature

#54 feat: keyExpression 추가 카드 퍼블리싱 + 링크 이동
  components/study/KeyExpression/LookingMore.tsx
  components/study/KeyExpression/index.tsx
  public/assets/icons/arrow.svg
  public/assets/images/keyExpressionImage.svg
Labels: 🥝. feature

#56 feat: my vocab - server 연결
  components/mypage/myvocab/MyVocab.tsx
Labels: 🥝. feature

#57 feat: mycollection 페이지 데이터 없을 때 분기처리 구현
  components/mypage/mysong/Mysong.tsx
  components/mypage/myvocab/MyVocab.tsx
  pages/mypage/collection.tsx
Labels: 🥝. feature

#58 hotfix: y에서 Y로 수정
  components/study/PlayerBtns.tsx
Labels: 🥝. feature
